# Additional Data Transformation

In this notebook, we will do the transformations discussed in EDA.

In [25]:
# Import libraries and read in data
import pandas as pd

elec_path = r"C:\Users\Admin\Desktop\net-zero emission by 2025 project\net-zero-emission-data-analytics-project\cleaned datasets\elec_gen_and_consump.csv"
ghg_path = r"C:\Users\Admin\Desktop\net-zero emission by 2025 project\net-zero-emission-data-analytics-project\cleaned datasets\ggas_emissions.csv"

elec_gen_and_consump = pd.read_csv(elec_path)
ggas_emissions = pd.read_csv(ghg_path)

In [26]:
elec_gen_and_consump.head()

   year            category              data_series    value
0  2025               Total   Electricity Generation  60410.4
1  2024               Total   Electricity Generation  59616.1
2  2024               Total  Electricity Consumption  57639.7
3  2024  Consumption Sector       Industrial-Related  22704.0
4  2024  Consumption Sector            Manufacturing  20630.5

In [27]:
ggas_emissions.head()

   year  category                     data_series  value
0  2023     Total  Total Greenhouse Gas Emissions   55.5
1  2023  Gas Type            Carbon Dioxide (CO2)   48.2
2  2023  Gas Type                   Methane (CH4)    0.1
3  2023  Gas Type             Nitrous Oxide (N2O)    0.5
4  2023  Gas Type       Hydrofluorocarbons (HFCs)    4.0

In both of these datasets, we can see that there is total, and there's another description for each dataset. Therefore, we will split out rows that represent total value to as separate datsets. First, we will begin with electricity generation and consumption dataset.

In [28]:
# Separate total electricity generation and consumption
elec_gen_and_consump_total = elec_gen_and_consump[
    elec_gen_and_consump['category'] == 'Total'
].copy()

# Remove the category column
elec_gen_and_consump_total = elec_gen_and_consump_total.drop(
    columns=['category']
)

# Preview
display(elec_gen_and_consump_total.head())

    year              data_series    value
0   2025   Electricity Generation  60410.4
1   2024   Electricity Generation  59616.1
2   2024  Electricity Consumption  57639.7
19  2023   Electricity Generation  57384.2
20  2023  Electricity Consumption  55426.4

Now we will remove total rows in the original dataset, and also remove the category column since all rows represent Consumption Sector now.

In [29]:
# Separate consumption sector data
elec_gen_and_consump_sector = elec_gen_and_consump[
    elec_gen_and_consump['category'] != 'Total'
].copy()

# Remove the category column
elec_gen_and_consump_sector = elec_gen_and_consump_sector.drop(
    columns=['category']
)

# Preview
display(elec_gen_and_consump_sector.head())

   year               data_series    value
3  2024        Industrial-Related  22704.0
4  2024             Manufacturing  20630.5
5  2024              Construction    440.0
6  2024                 Utilities   1569.4
7  2024  Other Industrial-Related     64.1

To make sure there are no missing or duplicate values, we will perform a check in the following cell.

In [30]:
# Check missing values
print("Missing values - elec_gen_and_consump_total:")
print(elec_gen_and_consump_total.isnull().sum())

print("\nMissing values - elec_gen_and_consump_sector:")
print(elec_gen_and_consump_sector.isnull().sum())


# Check duplicate rows
print("\nDuplicate rows - elec_gen_and_consump_total:")
print(elec_gen_and_consump_total.duplicated().sum())

print("\nDuplicate rows - elec_gen_and_consump_sector:")
print(elec_gen_and_consump_sector.duplicated().sum())

Missing values - elec_gen_and_consump_total:
year           0
data_series    0
value          0
dtype: int64

Missing values - elec_gen_and_consump_sector:
year           0
data_series    0
value          0
dtype: int64

Duplicate rows - elec_gen_and_consump_total:
0

Duplicate rows - elec_gen_and_consump_sector:
0

Next, we will move on to doing similar transformations to greenhouse gas emissions dataset.

In [31]:
ggas_emissions

     year  category                     data_series  value
0    2023     Total  Total Greenhouse Gas Emissions   55.5
1    2023  Gas Type            Carbon Dioxide (CO2)   48.2
2    2023  Gas Type                   Methane (CH4)    0.1
3    2023  Gas Type             Nitrous Oxide (N2O)    0.5
4    2023  Gas Type       Hydrofluorocarbons (HFCs)    4.0
..    ...       ...                             ...    ...
187  2000  Gas Type             Nitrous Oxide (N2O)    0.3
188  2000  Gas Type       Hydrofluorocarbons (HFCs)    0.1
189  2000  Gas Type         Perfluorocarbons (PFCs)    0.8
190  2000  Gas Type      Sulphur Hexafluoride (SF6)    0.0
191  2000  Gas Type      Nitrogen Trifluoride (NF3)    0.1

[192 rows x 4 columns]

In [32]:
# Separate total GHG emissions
ggas_emissions_total = ggas_emissions[
    ggas_emissions['category'] == 'Total'
].copy()

# Remove category column from total dataset
ggas_emissions_total = ggas_emissions_total.drop(
    columns=['category']
)

# Remove total rows from original dataset, keeping only gas types
ggas_emissions_gas_type = ggas_emissions[
    ggas_emissions['category'] != 'Total'
].copy()

# Remove category column from gas-type dataset
ggas_emissions_gas_type = ggas_emissions_gas_type.drop(
    columns=['category']
)

In [33]:
display(ggas_emissions_total.head())

    year                     data_series  value
0   2023  Total Greenhouse Gas Emissions   55.5
8   2022  Total Greenhouse Gas Emissions   58.6
16  2021  Total Greenhouse Gas Emissions   58.3
24  2020  Total Greenhouse Gas Emissions   53.9
32  2019  Total Greenhouse Gas Emissions   55.6

In [34]:
display(ggas_emissions_gas_type.head())

   year                data_series  value
1  2023       Carbon Dioxide (CO2)   48.2
2  2023              Methane (CH4)    0.1
3  2023        Nitrous Oxide (N2O)    0.5
4  2023  Hydrofluorocarbons (HFCs)    4.0
5  2023    Perfluorocarbons (PFCs)    2.1

In [35]:
# Check missing values

print("Missing values - ggas_emissions_total:")
print(ggas_emissions_total.isnull().sum())

print("\nMissing values - ggas_emissions_gas_type:")
print(ggas_emissions_gas_type.isnull().sum())

# Check duplicate rows

print("\nDuplicate rows - ggas_emissions_total:")
print(ggas_emissions_total.duplicated().sum())

print("\nDuplicate rows - ggas_emissions_gas_type:")
print(ggas_emissions_gas_type.duplicated().sum())

Missing values - ggas_emissions_total:
year           0
data_series    0
value          0
dtype: int64

Missing values - ggas_emissions_gas_type:
year           0
data_series    0
value          0
dtype: int64

Duplicate rows - ggas_emissions_total:
0

Duplicate rows - ggas_emissions_gas_type:
0

The results above show transformation is successfully done and the datasets are clean. Now we will export the cleaned datasets as csv files.

In [36]:
# Export transformed datasets as CSV
output_path = r"C:\Users\Admin\Desktop\net-zero emission by 2025 project\net-zero-emission-data-analytics-project\cleaned datasets"

elec_gen_and_consump_total.to_csv(
    output_path + r"\elec_gen_and_consump_total.csv",
    index=False
)

elec_gen_and_consump_sector.to_csv(
    output_path + r"\elec_gen_and_consump_sector.csv",
    index=False
)

ggas_emissions_total.to_csv(
    output_path + r"\ggas_emissions_total.csv",
    index=False
)

ggas_emissions_gas_type.to_csv(
    output_path + r"\ggas_emissions_gas_type.csv",
    index=False
)